import {
  Attachment,
  GetRequisitionsResponseModel,
} from './requisition.interfaces';

export const REQUISITION_DATA: GetRequisitionsResponseModel = {
  requisitions: [
    {
      requisitionId: 'A123BCD',
      dateReceived: '2022-11-25T14:00:05.2218382+00:00',
      repliedToHmlr: null,
      requisitions: [
        {
          attachmentId: null,
          copyType: 1,
          docType: 8,
          filename: 'Land Registry Documents',
          blobUrl:
            'hmlr/docs/eDRS/2022-11-25/1516313_Land Registry Documents.PDF',
          format: 0,
          data: null,
          sentToHmlr: false,
          sentToHmlrDate: null,
          acceptedHmlr: false,
          acceptedOrRejectedDate: null,
          supportingDocumentIdUniqueKey: null,
        },
      ],
      dateReplied: null,
      requisitionReplies: null,
    },
  ],
  orderId: 1516313,
  serviceType: 0,
  submissionStatus: 2,
  hmlrUserId: null,
  hmlrPassword: null,
  hmlrSubmissionId: '7fe20f91-b115-4b29-bfec-13ec36b0eb79',
  clientKey: null,
  error: null,
  audit: {
    username: null,
    name: 'System',
    userId: null,
    applicationId: null,
    applicationName: null,
    operation: 'DRSService GetRequisitionsAysnc',
    dateRequested: '2022-11-28T10:15:03.8199336+00:00',
  },
  id: null,
  partitionKey: null,
};

export const APPLICATION_DATA: Attachment[] = [
  {
    attachmentId: '36',
    copyType: 0,
    docType: 0,
    filename: '14 Dawberry Transfer deed.pdf',
    blobUrl:
      'https://ddintegrationsdevelop.blob.core.windows.net/integration-develop/Blank.pdf',
    format: 0,
    data: null,
    sentToHmlr: false,
    sentToHmlrDate: null,
    acceptedHmlr: false,
    acceptedOrRejectedDate: null,
    supportingDocumentIdUniqueKey: null,
  },
  {
    attachmentId: '37',
    copyType: 0,
    docType: 0,
    filename: '14 Dawberry mortgage deed.pdf',
    blobUrl:
      'https://ddintegrationsdevelop.blob.core.windows.net/integration-develop/Blank.pdf',
    format: 0,
    data: null,
    sentToHmlr: false,
    sentToHmlrDate: null,
    acceptedHmlr: false,
    acceptedOrRejectedDate: null,
    supportingDocumentIdUniqueKey: null,
  },
  {
    attachmentId: '3',
    copyType: 0,
    docType: 0,
    filename: '14 Dawberry SDLT Transactions Report_6253_007.pdf',
    blobUrl:
      'https://ddintegrationsdevelop.blob.core.windows.net/integration-develop/Blank.pdf',
    format: 0,
    data: null,
    sentToHmlr: false,
    sentToHmlrDate: null,
    acceptedHmlr: false,
    acceptedOrRejectedDate: null,
    supportingDocumentIdUniqueKey: null,
  },
  {
    attachmentId: '4',
    copyType: 0,
    docType: 0,
    filename: '14 Dawberry Grant of Probate_6253_1656525687251.pdf',
    blobUrl:
      'https://ddintegrationsdevelop.blob.core.windows.net/integration-develop/Blank.pdf',
    format: 0,
    data: null,
    sentToHmlr: false,
    sentToHmlrDate: null,
    acceptedHmlr: false,
    acceptedOrRejectedDate: null,
    supportingDocumentIdUniqueKey: null,
  },
  {
    attachmentId: '38',
    copyType: 0,
    docType: 0,
    filename: 'xyz.pdf',
    blobUrl: 'hmlr/docs/eDRS/2022-11-25/1516313_xyz.pdf.Pdf',
    format: 0,
    data: null,
    sentToHmlr: false,
    sentToHmlrDate: null,
    acceptedHmlr: false,
    acceptedOrRejectedDate: null,
    supportingDocumentIdUniqueKey: null,
  },
];
