export enum SupportingDocumentType {
  Abstract = 1,
  Agreement = 2,
  Assent = 3,
  Assignment = 4,
  BirthCertificate = 5,
  Charge = 6,
  Conveyance = 7,
  Correspondence = 8,
  CourtOrder = 9,
  DeathCertificate = 10,
  Deed = 11,
  Discharge = 12,
  DocumentList = 13,
  Evidence = 14,
  EX1A = 15,
  FormDI = 16,
  IdentityEvidence = 17,
  IdentityForm = 18,
  Indenture = 19,
  LandTransactionTax = 20,
  LastingPOASummary = 21,
  Lease = 22,
  License = 23,
  LRCorrespondence = 24,
  MarriageCertificate = 25,
  Plan = 26,
  PowerofAttorney = 27,
  Probate = 28,
  StampDutyLandTax = 29,
  StatementOfTruth = 30,
  StatutoryDeclaration = 31,
  SubCharge = 32,
  Transfer = 33,
  WitnessStatement = 34,
}

export enum SupportingDocumentCopyType {
  Original = 1,
  Certified = 2,
  Scanned = 3,
}

export const SupportingDocumentCopyTypeText = new Map<number, string>([
  [SupportingDocumentCopyType.Original, 'Original'],
  [SupportingDocumentCopyType.Certified, 'Certified'],
  [SupportingDocumentCopyType.Scanned, 'Scanned'],
]);

export const SupportingDocumentTypeText = new Map<number, string>([
  [SupportingDocumentType.Abstract, 'Abstract'],
  [SupportingDocumentType.Agreement, 'Agreement'],
  [SupportingDocumentType.Assent, 'Assent'],
  [SupportingDocumentType.Assignment, 'Assignment'],
  [SupportingDocumentType.BirthCertificate, 'Birth Certificate'],
  [SupportingDocumentType.Charge, 'Charge'],
  [SupportingDocumentType.Conveyance, 'Conveyance'],
  [SupportingDocumentType.Correspondence, 'Correspondence'],
  [SupportingDocumentType.CourtOrder, 'Court Order'],
  [SupportingDocumentType.DeathCertificate, 'Death Certificate'],
  [SupportingDocumentType.Deed, 'Deed'],
  [SupportingDocumentType.Discharge, 'Discharge'],
  [SupportingDocumentType.DocumentList, 'Document List'],
  [SupportingDocumentType.Evidence, 'Evidence'],
  [SupportingDocumentType.EX1A, 'EX1A'],
  [SupportingDocumentType.FormDI, 'Form DI'],
  [SupportingDocumentType.IdentityEvidence, 'Identity Evidence'],
  [SupportingDocumentType.IdentityForm, 'Identity Form'],
  [SupportingDocumentType.Indenture, 'Indenture'],
  [SupportingDocumentType.LandTransactionTax, 'Land Transaction Tax'],
  [SupportingDocumentType.LastingPOASummary, 'Lasting POA Summary'],
  [SupportingDocumentType.Lease, 'Lease'],
  [SupportingDocumentType.License, 'License'],
  [SupportingDocumentType.LRCorrespondence, 'LR Correspondence'],
  [SupportingDocumentType.MarriageCertificate, 'Marriage Certificate'],
  [SupportingDocumentType.Plan, 'Plan'],
  [SupportingDocumentType.PowerofAttorney, 'Power of Attorney'],
  [SupportingDocumentType.Probate, 'Probate'],
  [SupportingDocumentType.StampDutyLandTax, 'Stamp Duty Land Tax'],
  [SupportingDocumentType.StatementOfTruth, 'Statement Of Truth'],
  [SupportingDocumentType.StatutoryDeclaration, 'Statutory Declaration'],
  [SupportingDocumentType.SubCharge, 'Sub Charge'],
  [SupportingDocumentType.Transfer, 'Transfer'],
  [SupportingDocumentType.WitnessStatement, 'Witness Statement'],
]);
